# -*- coding: utf-8 -*-
"""Instagram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1axPGqoywBghlK2JZ7MLKmxwgdpi4ij_e
"""

import pandas as pd

df=pd.read_csv('/content/comments.csv')

df.head()

df.isnull().sum()

df.info()

"""## Data Cleaning"""

# Convert 'created Timestamp' to datetime objects
df['created Timestamp'] = pd.to_datetime(df['created Timestamp'], format='%d-%m-%Y %H:%M', errors='coerce')

# Extract the year from 'created Timestamp' to use for 'posted date'
df['temp_year'] = df['created Timestamp'].dt.year

# Create a full date string for 'posted date' by combining the month/day from 'posted date' with the year from 'created Timestamp'
df['full_posted_date_str'] = df['posted date'] + ' ' + df['temp_year'].astype(str)

# Convert the new full date string to datetime objects
df['posted date'] = pd.to_datetime(df['full_posted_date_str'], format='%B %d %Y', errors='coerce')

# Drop the temporary columns
df = df.drop(columns=['temp_year', 'full_posted_date_str'])

# Display the info again to confirm data types and non-null counts
df.info()

"""## Engagement Metrics"""

# Calculate comments per photo
comments_per_photo = df.groupby('Photo id').size().sort_values(ascending=False)

print('Comments per Photo:')
print(comments_per_photo.head())

# Visualize top 10 photos by comment count
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
comments_per_photo.head(10).plot(kind='bar')
plt.title('Top 10 Photos by Comment Count')
plt.xlabel('Photo ID')
plt.ylabel('Number of Comments')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### Comment Activity Over Time"""

# Analyze daily comment activity based on 'created Timestamp'
daily_comment_activity = df['created Timestamp'].dt.date.value_counts().sort_index()

plt.figure(figsize=(12, 6))
daily_comment_activity.plot(kind='line', marker='o')
plt.title('Daily Comment Activity (based on Created Timestamp)')
plt.xlabel('Date')
plt.ylabel('Number of Comments')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print('Daily Comment Activity:')
print(daily_comment_activity.head())

"""Next, let's examine comment activity by day of the week and hour of the day to identify patterns."""

# Analyze comment activity by day of the week
df['day_of_week'] = df['created Timestamp'].dt.day_name()
day_of_week_activity = df['day_of_week'].value_counts().reindex([
    'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'
])

plt.figure(figsize=(10, 5))
day_of_week_activity.plot(kind='bar')
plt.title('Comment Activity by Day of Week')
plt.xlabel('Day of Week')
plt.ylabel('Number of Comments')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print('\nComment Activity by Day of Week:')
print(day_of_week_activity)

# Analyze comment activity by hour of the day
df['hour_of_day'] = df['created Timestamp'].dt.hour
hour_of_day_activity = df['hour_of_day'].value_counts().sort_index()

plt.figure(figsize=(12, 6))
hour_of_day_activity.plot(kind='bar')
plt.title('Comment Activity by Hour of Day')
plt.xlabel('Hour of Day')
plt.ylabel('Number of Comments')
plt.xticks(rotation=0)
plt.grid(axis='y')
plt.tight_layout()
plt.show()

print('\nComment Activity by Hour of Day:')
print(hour_of_day_activity.head())

"""## Hashtag Analysis"""

import re

# The previous hashtag extraction failed because the 'comment' column does not contain '#' symbols.
# We will instead analyze the 'Hashtags used count' column.

print("Analysis of 'Hashtags used count':")
print(df['Hashtags used count'].value_counts().sort_index())

# Visualize the distribution of 'Hashtags used count'
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
df['Hashtags used count'].value_counts().sort_index().plot(kind='bar')
plt.title('Distribution of Hashtags Used per Comment')
plt.xlabel('Number of Hashtags')
plt.ylabel('Number of Comments')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""## Content Types Analysis"""

emoji_usage = df['emoji used'].value_counts(normalize=True) * 100

print('Proportion of Comments with Emojis:')
print(emoji_usage)

plt.figure(figsize=(8, 6))
emoji_usage.plot(kind='bar', color=['skyblue', 'lightcoral'])
plt.title('Proportion of Comments with Emojis')
plt.xlabel('Emoji Used')
plt.ylabel('Percentage')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()









